import Link from "next/link";
import { ArrowRight } from "lucide-react";

export const metadata = {
  title: { absolute: "About Us | BiyondBytes" },
  description: "At BiyondBytes, we empower writers, developers, and designers to showcase their talents by providing a platform to create and share high-quality content.",
};

const stats = [
  { label: "Active Writers", value: "500+" },
  { label: "Published Articles", value: "2,000+" },
  { label: "Monthly Readers", value: "50K+" },
];

const offerings = [
  { title: "Blog Writing", description: "Writers publish engaging posts across topics and earn a share of ad revenue generated by their content." },
  { title: "Web Development", description: "Resources and support for developers to showcase skills and collaborate on real-world projects." },
  { title: "Product Design", description: "Designers share concepts and collaborate with professionals across the industry." },
];

export default function Page() {
  return (
    <div className="min-h-screen bg-[#FAFAFA] pt-24 pb-20">

      {/* Hero */}
      <section className="bb-container max-w-[860px] mb-20">
        <div className="flex items-center gap-2 mb-6">
          <span className="w-6 h-px bg-bb-accent" />
          <span className="text-[11px] font-bold tracking-[0.2em] uppercase text-bb-accent">About BiyondBytes</span>
        </div>
        <h1 className="font-serif text-[clamp(2.2rem,5vw,4rem)] font-bold text-[rgb(9,9,11)] leading-[1.08] tracking-tight mb-6">
          Empowering creators to share knowledge that matters.
        </h1>
        <p className="text-lg text-[rgb(113,113,122)] leading-relaxed max-w-2xl">
          At BiyondBytes, we aim to empower writers, developers, and designers to showcase their talents by providing a platform to create and share high-quality content.
        </p>
      </section>

      {/* Stats */}
      <section className="bb-container max-w-[860px] mb-20">
        <div className="grid grid-cols-3 gap-8 border-y border-gray-100 py-12">
          {stats.map((s) => (
            <div key={s.label} className="text-center">
              <p className="font-serif text-4xl font-bold text-[rgb(9,9,11)] mb-1">{s.value}</p>
              <p className="text-sm text-[rgb(113,113,122)]">{s.label}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Mission */}
      <section className="bb-container max-w-[860px] mb-20">
        <h2 className="font-serif text-2xl font-bold text-[rgb(9,9,11)] mb-4">Our Mission</h2>
        <p className="text-[rgb(113,113,122)] leading-relaxed max-w-2xl">
          We believe everyone has a story worth telling and knowledge worth sharing. Our platform makes it simple and rewarding to publish content that reaches and inspires readers worldwide.
        </p>
      </section>

      {/* Offerings */}
      <section className="bb-container max-w-[860px] mb-20">
        <h2 className="font-serif text-2xl font-bold text-[rgb(9,9,11)] mb-8">What We Offer</h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {offerings.map((item) => (
            <div key={item.title} className="bg-white rounded-2xl border border-gray-100 p-6 hover:shadow-sm transition-shadow">
              <h3 className="font-serif text-lg font-bold text-[rgb(9,9,11)] mb-3">{item.title}</h3>
              <p className="text-sm text-[rgb(113,113,122)] leading-relaxed">{item.description}</p>
            </div>
          ))}
        </div>
      </section>

      {/* CTA */}
      <section className="bb-container max-w-[860px]">
        <div className="bg-[rgb(24,24,27)] rounded-3xl p-10 md:p-14 text-center">
          <h2 className="font-serif text-3xl font-bold text-white mb-4">Ready to Get Started?</h2>
          <p className="text-white/60 mb-8 max-w-md mx-auto leading-relaxed">
            Join our community to start writing, developing, or designing. There&apos;s a place for you at BiyondBytes.
          </p>
          <div className="flex flex-col sm:flex-row gap-3 justify-center">
            <Link href="/byAuthBtn" className="inline-flex items-center gap-2 px-6 py-3 bg-white text-[rgb(9,9,11)] rounded-full font-semibold text-sm hover:bg-gray-100 transition-colors">
              Start Writing <ArrowRight className="w-4 h-4" />
            </Link>
            <Link href="/contact-us" className="inline-flex items-center gap-2 px-6 py-3 border border-white/20 text-white rounded-full font-semibold text-sm hover:bg-white/10 transition-colors">
              Contact Us
            </Link>
          </div>
        </div>
      </section>
    </div>
  );
}
